eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
      defaultZone : ${EUREKA_SERVER-ADDRESS:http:http://localhost:8761/}
